config/routes.rb
LeagueAppointmentsRails::Application.routes.draw do

  resources :matches

  resources :players

  resources :leagues do
    resources :divisions
  end

  root :to => 'welcome#index'

end

app/models/league.rb
class League
  include Mongoid::Document
  field :title, type: String
  field :start_date, type: Date
  field :end_date, type: Date
  
  has_many :divisions
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    @league = League.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.json
  def new
    @league = League.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/1/edit
  def edit
    @league = League.find(params[:id])
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.json
  def update
    @league = League.find(params[:id])

    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league = League.find(params[:id])
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :title %><br />
  <%= f.text_field :title %><br />
  <%= f.label :start_date %><br />
  <%= f.text_field :start_date %><br />
  <%= f.label :end_date %><br />
  <%= f.text_field :end_date %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render 'form' %>
<%= render 'divisions/list', league: @league %>
<%= link_to 'Add Division', new_league_division_path(@league) %> |
<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<h1>Listing leagues</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leagues.each do |league| %>
  <tr>
	<td><h4><%= league.title %></h4></td>
    <td><%= link_to 'Show', league %></td>
    <td><%= link_to 'Edit', edit_league_path(league) %></td>
    <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<h4><%= @league.title %></h4><br/>
Start Date: <%= @league.start_date %><br/>
End Date: <%= @league.end_date %><br/>
Number of divisions: <%= @league.divisions.size%><br/><br/>
<%= render 'divisions/list', league: @league %>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>