config/routes.rb
LeagueAppointmentsRails::Application.routes.draw do

  resources :matches

  resources :players

  resources :leagues do
    resources :divisions
  end

  root :to => 'welcome#index'

end

app/models/division.rb
class Division
  include Mongoid::Document
  field :league, type: String
  field :title, type: String
  
  belongs_to :league
  has_and_belongs_to_many :players, inverse_of: :divisions
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  # GET /divisions
  # GET /divisions.json
  
  #before_action :set_league
  
  def index
    @league = League.find(params[:league_id])
    @divisions = @league.divisions

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.json
  def new
    @league = League.find(params[:league_id])
    @division = @league.divisions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @league = League.find(params[:league_id])
    @division = @league.divisions.build(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division.league, notice: 'Division was successfully created.' }
        format.json { render json: @division, status: :created, location: @division }
      else
        format.html { render action: "new" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.json
  def update
    @division = Division.find(params[:id])
    @division.players << Player.find(params[:player_id]) if params[:player_id]

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to league_divisions_url(params[:league_id]) }
      format.json { head :no_content }
    end
  end
  
  private
  
  def set_league
    @league = League.find(params[:league_id])
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_for [@league, @division] do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Division Number' %><br />
  <%= f.text_field :title %><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/divisions/_list.html.erb
<% unless league.divisions.empty? %>
Divisions:<br/>
  <% league.divisions.each do |division|%>
    <%= link_to division.title, [division.league, division] %><br/>
  <% end %>
  <br/><br/>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>
League: <%= @division.league.title %><br/>
<%= render 'form' %>
Number of Players: <%= @division.players.size %><br/><br/>
<%= render 'players/list', division: @division %><br/><br/>
Full List of Players:<br/>
<% Player.all.each do |player|%>
  <%= form_for [@division.league, @division] do |f| %>
    <input name="player_id" type="hidden" value="<%= player.id %>" />
    <%= player.name %>
	<%= f.submit 'Add Player to Division' %>
  <% end %>	
<% end %>


<%= link_to 'Show', [@division.league, @division] %> |
<%= link_to 'Back', league_divisions_path(@division.league) %>

app/views/divisions/index.html.erb
<h1>Listing divisions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
League: <%= @league.title %>
<% @divisions.each do |division| %>
  <tr>
	<td><h4><%= division.title %></h4>&nbsp;&nbsp;</td>
    <td><%= link_to 'Show', division %></td>
    <td><%= link_to 'Edit', edit_division_path(division) %></td>
    <td><%= link_to 'Destroy', division, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Division', new_league_division_path(@league) %>

app/views/divisions/new.html.erb
<h1>New division</h1>
League: <%= @division.league.title %><br/>
<%= render 'form' %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>
League: <%= @division.league.title %><br/>
Division Number: <%= @division.title %><br/>
Number of Players: <%= @division.players.size %><br/><br/>
<%= render 'players/list', division: @division %>

<%= link_to 'Edit', edit_league_division_path(@division.league, @division) %> <br/>
<%= link_to 'Destroy', [@division.league, @division], method: :delete, data: { confirm: 'Are you sure?' } %>