config/routes.rb
LeagueAppointmentsRails::Application.routes.draw do

  resources :matches

  resources :players

  resources :leagues do
    resources :divisions
  end

  root :to => 'welcome#index'

end

app/models/match.rb
class Match
  include Mongoid::Document
  field :schedule_for, type: Date,
  field :schedule_accepted, type: Boolean,
  field :schedule_accepted_by, type: Player,
  field :played_on, type: Date,
  field :result, type: String,
  field :winner, type: Player,
  field :scheduled_by, type: Player,
  field :division, type: Division,
  field :potential_oponents, type: Array,
  field :player1, type: Player,
  field :player2, type: Player,
  field :loser, type: Player
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :schedule_for %><br />
    <%= f.text_field :schedule_for %>
  </div>
  <div class="field">
    <%= f.label :schedule_accepted %><br />
    <%= f.text_field :schedule_accepted %>
  </div>
  <div class="field">
    <%= f.label :schedule_accepted_by %><br />
    <%= f.text_field :schedule_accepted_by %>
  </div>
  <div class="field">
    <%= f.label :played_on %><br />
    <%= f.text_field :played_on %>
  </div>
  <div class="field">
    <%= f.label :result %><br />
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :winner %><br />
    <%= f.text_field :winner %>
  </div>
  <div class="field">
    <%= f.label :scheduled_by %><br />
    <%= f.text_field :scheduled_by %>
  </div>
  <div class="field">
    <%= f.label :division %><br />
    <%= f.text_field :division %>
  </div>
  <div class="field">
    <%= f.label :potential_oponents %><br />
    <%= f.text_field :potential_oponents %>
  </div>
  <div class="field">
    <%= f.label :player1 %><br />
    <%= f.text_field :player1 %>
  </div>
  <div class="field">
    <%= f.label :player2 %><br />
    <%= f.text_field :player2 %>
  </div>
  <div class="field">
    <%= f.label :loser %><br />
    <%= f.text_field :loser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Schedule for</th>
    <th>Schedule accepted</th>
    <th>Schedule accepted by</th>
    <th>Played on</th>
    <th>Result</th>
    <th>Winner</th>
    <th>Scheduled by</th>
    <th>Division</th>
    <th>Potential oponents</th>
    <th>Player1</th>
    <th>Player2</th>
    <th>Loser</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.schedule_for %></td>
    <td><%= match.schedule_accepted %></td>
    <td><%= match.schedule_accepted_by %></td>
    <td><%= match.played_on %></td>
    <td><%= match.result %></td>
    <td><%= match.winner %></td>
    <td><%= match.scheduled_by %></td>
    <td><%= match.division %></td>
    <td><%= match.potential_oponents %></td>
    <td><%= match.player1 %></td>
    <td><%= match.player2 %></td>
    <td><%= match.loser %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Schedule for:</b>
  <%= @match.schedule_for %>
</p>

<p>
  <b>Schedule accepted:</b>
  <%= @match.schedule_accepted %>
</p>

<p>
  <b>Schedule accepted by:</b>
  <%= @match.schedule_accepted_by %>
</p>

<p>
  <b>Played on:</b>
  <%= @match.played_on %>
</p>

<p>
  <b>Result:</b>
  <%= @match.result %>
</p>

<p>
  <b>Winner:</b>
  <%= @match.winner %>
</p>

<p>
  <b>Scheduled by:</b>
  <%= @match.scheduled_by %>
</p>

<p>
  <b>Division:</b>
  <%= @match.division %>
</p>

<p>
  <b>Potential oponents:</b>
  <%= @match.potential_oponents %>
</p>

<p>
  <b>Player1:</b>
  <%= @match.player1 %>
</p>

<p>
  <b>Player2:</b>
  <%= @match.player2 %>
</p>

<p>
  <b>Loser:</b>
  <%= @match.loser %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>